### ISSUE TITLE
Images for README.

### ISSUE THREAD

**Issue by DarryQueen** [DarryQueen/Lynx#24]
![submissionimg-01](https://cloud.githubusercontent.com/assets/5403584/6320185/8db97642-ba8c-11e4-980a-f0631cad6689.jpg)
![submissionimg-02](https://cloud.githubusercontent.com/assets/5403584/6320188/8dbbcea6-ba8c-11e4-83b7-578a46497f78.jpg)
![submissionimg-03](https://cloud.githubusercontent.com/assets/5403584/6320184/8db9699a-ba8c-11e4-802d-4ae7926861e0.jpg)
![submissionimg-04](https://cloud.githubusercontent.com/assets/5403584/6320186/8db9881c-ba8c-11e4-8220-78b573d63309.jpg)
![submissionimg-05](https://cloud.githubusercontent.com/assets/5403584/6320187/8db9c82c-ba8c-11e4-8a56-c3f4948aa8ad.jpg)
![lynx_layouts-01](https://cloud.githubusercontent.com/assets/5403584/6320271/0774d232-ba8e-11e4-9ef0-6f1b7cf69a1f.png)
![lynx_layouts-02](https://cloud.githubusercontent.com/assets/5403584/6320272/0784f554-ba8e-11e4-9005-9477b29c68b5.png)
![lynx_layouts-04](https://cloud.githubusercontent.com/assets/5403584/6320273/0789e50a-ba8e-11e4-97ac-7f2b5668d832.png)
![lynx_layouts-05](https://cloud.githubusercontent.com/assets/5403584/6320292/578f6516-ba8e-11e4-859c-1bf76e1b4b4b.png)
![lynx_layouts-06](https://cloud.githubusercontent.com/assets/5403584/6320274/078d5406-ba8e-11e4-902f-bc942eaaaa65.png)

**Comment by dianecw** [comment]
![lynx_overview](https://cloud.githubusercontent.com/assets/6895346/6344040/4767b458-bba7-11e4-9c32-12a8d8678f8d.jpg)
