### ISSUE TITLE
Look into geolocation tracking

### ISSUE THREAD

**Issue by dianecw** [DarryQueen/Lynx#3]

**Comment by DarryQueen** [comment]
Geolocation is unfeasible; standard GPS isn't precise enough for our use case.
NFC is also no-go; Android NFC mandates that devices be literally touching.

Look into Bluetooth RSSI-to-distance formulas; these are rough but likely all we need.

**Comment by DarryQueen** [comment]
Used Bluetooth RSSI to determine distance. Very rough, but works for our case where the device and its hardware are constant.
